version: '3.5'

networks : 
  localdev:
    name: localdev

services:
 web:
    image: lsilverio18/ecommerce-produto
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - localdev
